{
  "language": "ruby",
  "cache": "bundler",
  "rvm": "2.5.0",
  "services": [
    "postgresql"
  ],
  "before_script": [
    "psql -c 'create database travis_rspec_test;' -U postgres",
    "cp config/database.travis.yml config/database.yml",
  ],
  "script": [
    "bundle exec rake db:schema:load",
    "bundle exec rake db:test:prepare",
    "bundle exec rspec && bundle exec rspec --only-failures"
  ],
  "after_script": [
    "echo $TRAVIS_TEST_RESULT"
  ],
  "os": "linux",
  "group": "stable",
  "dist": "trusty"
}
